name: diy-components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - cadquery>=2.4.0
      - cadquery-ocp>=7.7.0
      - build123d>=0.10.0
      - pytest
